name: noise_protocol
version: 0.1.0
homepage: https://github.com/dint-dev/cryptography
description:
  A Dart implementation of Noise protocol, which can be used for securing communications (E2EE,
  etc.).

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  collection: ^1.14.0
  cryptography: ^0.3.5
  meta: ^1.1.0
  kms: ^0.4.0
  typed_data: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0

dependency_overrides:
  cryptography:
    path: '../cryptography'
  kms:
    path: '../kms'