name: jwk
version: 0.1.1
homepage: https://github.com/dint-dev/cryptography
description: JWK (JSON Web Key) encoding and decoding (for package:cryptography).

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  cryptography: ^2.0.5

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.0

dependency_overrides:
  cryptography:
    path: ../cryptography