name: cryptography_flutter_integration_test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  cryptography_test: ^0.1.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: '>=3.0.0 <7.0.0' # A large range is needed because we support old Flutter SDKs

flutter:
  uses-material-design: true

dependency_overrides:
  cryptography:
    path: ../cryptography
  cryptography_flutter:
    path: ../cryptography_flutter
  cryptography_test:
    path: ../cryptography_test