name: cryptography
version: 2.9.0
homepage: https://github.com/dint-dev/cryptography
description:
  Cryptographic algorithms for encryption, digital signatures, key agreement, authentication, and
  hashing. AES, Chacha20, ED25519, and more. Cross-platform (mobile, desktop, JS, WASM).
topics:
 - crypto

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  #
  # Packages by Google:
  #
  collection: ^1.17.0
  crypto: ^3.0.3
  ffi: ^2.1.0
  meta: ^1.8.0
  typed_data: ^1.3.0

dev_dependencies:
  #
  # Packages by Google:
  #
  lints: '>=3.0.0 <7.0.0' # A large range is needed because we support old Flutter SDKs
  test: ^1.24.0
