name: cryptography
version: 1.4.1
homepage: https://github.com/dint-dev/cryptography
description:
  Cryptographic algorithms for encryption, digital signatures, key agreement, authentication, and
  hashing. AES, Chacha20, ED25519, X25519, and more. Web Crypto support.

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  collection: ^1.10.0
  crypto: ^2.0.0
  fixnum: ^0.10.11
  js: ^0.6.0
  meta: ^1.1.0
  typed_data: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
