name: cryptography_test
version: 0.1.0
homepage: https://github.com/dint-dev/cryptography
description: A package for testing and benchmarking cryptographic algorithm implementations that
  implement "package:cryptography" interfaces.

environment:
  sdk: '>=3.3.0 <4.0.0'

# Open-source contributors:
#
# If you add a dependency to the package, please help
# readers of pubspec.yaml to understand who maintains it
# and any other useful information about it.
dependencies:
  #
  # Packages by Google:
  #
  collection: ^1.17.0
  crypto: ^3.0.3
  test: ^1.24.0
  typed_data: ^1.3.0

  #
  # Packages by github.com/dint-dev:
  #
  cryptography: ^2.8.0

dev_dependencies:
  #
  # Packages by Google:
  #
  lints: ^6.0.0

dependency_overrides:
  cryptography:
    path: ../cryptography