name: Publish to pub.dev

on:
  push:
    tags:
      - 'cryptography-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@daef289245bc5d4ab7864e0788a58108a9be6c99
    with:
      environment: pub.dev
      working-directory: ./cryptography